/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const buttonBase: string;

export {
	buttonBase
};

export default {
	buttonBase
};
