/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const page: string;
const latestText: string;
const subtitle: string;
const list: string;
const buttons: string;

export {
	page,
	latestText,
	subtitle,
	list,
	buttons
};

export default {
	page,
	latestText,
	subtitle,
	list,
	buttons
};
