/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const directoryNavigator: string;
const navigationButtons: string;
const backArrow: string;
const pathBar: string;
const navigatorSlices: string;
const jumpToSlicePathButton: string;
const settingsButton: string;
const settingsPanel: string;
const viewSection: string;
const timestampStyleButton: string;

export {
	directoryNavigator,
	navigationButtons,
	backArrow,
	pathBar,
	navigatorSlices,
	jumpToSlicePathButton,
	settingsButton,
	settingsPanel,
	viewSection,
	timestampStyleButton
};

export default {
	directoryNavigator,
	navigationButtons,
	backArrow,
	pathBar,
	navigatorSlices,
	jumpToSlicePathButton,
	settingsButton,
	settingsPanel,
	viewSection,
	timestampStyleButton
};
