/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const optionsList: string;
const optionItem: string;
const optionButton: string;
const regularSeparator: string;

export {
	optionsList,
	optionItem,
	optionButton,
	regularSeparator
};

export default {
	optionsList,
	optionItem,
	optionButton,
	regularSeparator
};
