/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const infoPanel: string;
const aboutArea: string;
const rowLabel: string;
const rowText: string;
const buttonPanel: string;
const paragraph: string;

export {
	infoPanel,
	aboutArea,
	rowLabel,
	rowText,
	buttonPanel,
	paragraph
};

export default {
	infoPanel,
	aboutArea,
	rowLabel,
	rowText,
	buttonPanel,
	paragraph
};
