/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const dataPage: string;
const heading: string;
const optionsPanel: string;
const updateStorageForm: string;
const replaceTextbox: string;

export {
	dataPage,
	heading,
	optionsPanel,
	updateStorageForm,
	replaceTextbox
};

export default {
	dataPage,
	heading,
	optionsPanel,
	updateStorageForm,
	replaceTextbox
};
