/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const subtleButton: string;

export {
	subtleButton
};

export default {
	subtleButton
};
